// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiPizzeria.Models;

#nullable disable

namespace WebApiPizzeria.Migrations
{
    [DbContext(typeof(PostgresContext))]
    partial class PostgresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiPizzeria.Models.ConversationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConversationState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_state");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("conversation_sessions_pkey");

                    b.HasIndex(new[] { "UserId" }, "conversation_sessions_user_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "LastUpdatedAt" }, "idx_conversation_sessions_last_updated");

                    b.ToTable("conversation_sessions", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.DayType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("day_types_pkey");

                    b.ToTable("day_types", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.ExtraType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ExtraTypes");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.N8nChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("message");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("n8n_chat_histories_pkey");

                    b.ToTable("n8n_chat_histories", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<int?>("OrderStateTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("order_state_type_id");

                    b.Property<decimal?>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("orders_pkey");

                    b.HasIndex("OrderStateTypeId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int?>("ParentOrderItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("order_items_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("ParentOrderItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.OrderItemExtras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExtraTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExtraTypeId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemExtras");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.OrderStateType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("order_state_type_pkey");

                    b.ToTable("order_state_type", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("product_type_id");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.ProductAvailabilityDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("DayTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("day_type_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("product_availability_days_pkey");

                    b.HasIndex("DayTypeId");

                    b.HasIndex(new[] { "ProductId", "DayTypeId" }, "uq_product_day")
                        .IsUnique();

                    b.ToTable("product_availability_days", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.ProductConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildProductId")
                        .HasColumnType("integer")
                        .HasColumnName("child_product_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("product_configurations_pkey");

                    b.HasIndex("ChildProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_configurations", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("product_types_pkey");

                    b.ToTable("product_types", (string)null);
                });

            modelBuilder.Entity("WebApiPizzeria.Models.Order", b =>
                {
                    b.HasOne("WebApiPizzeria.Models.OrderStateType", "OrderStateType")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStateTypeId");

                    b.Navigation("OrderStateType");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.OrderItem", b =>
                {
                    b.HasOne("WebApiPizzeria.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_order");

                    b.HasOne("WebApiPizzeria.Models.OrderItem", "ParentOrderItem")
                        .WithMany("ChildOrderItems")
                        .HasForeignKey("ParentOrderItemId");

                    b.HasOne("WebApiPizzeria.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_order_items_product");

                    b.Navigation("Order");

                    b.Navigation("ParentOrderItem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.OrderItemExtras", b =>
                {
                    b.HasOne("WebApiPizzeria.Models.ExtraType", "ExtraType")
                        .WithMany("OrderItemExtras")
                        .HasForeignKey("ExtraTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiPizzeria.Models.OrderItem", "OrderItem")
                        .WithMany("OrderItemExtras")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraType");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.Product", b =>
                {
                    b.HasOne("WebApiPizzeria.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_products_product_type");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.ProductAvailabilityDay", b =>
                {
                    b.HasOne("WebApiPizzeria.Models.DayType", "DayType")
                        .WithMany("ProductAvailabilityDays")
                        .HasForeignKey("DayTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_pad_day_type");

                    b.HasOne("WebApiPizzeria.Models.Product", "Product")
                        .WithMany("ProductAvailabilityDays")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_product_availability_days_product");

                    b.Navigation("DayType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.ProductConfiguration", b =>
                {
                    b.HasOne("WebApiPizzeria.Models.Product", "ChildProduct")
                        .WithMany()
                        .HasForeignKey("ChildProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_configurations_child_product");

                    b.HasOne("WebApiPizzeria.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_configurations_product");

                    b.Navigation("ChildProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.DayType", b =>
                {
                    b.Navigation("ProductAvailabilityDays");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.ExtraType", b =>
                {
                    b.Navigation("OrderItemExtras");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.OrderItem", b =>
                {
                    b.Navigation("ChildOrderItems");

                    b.Navigation("OrderItemExtras");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.OrderStateType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductAvailabilityDays");
                });

            modelBuilder.Entity("WebApiPizzeria.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
